FROM docker.io/library/ubuntu:22.04

RUN apt-get update -y && apt-get install -y nano gnupg wget curl jq dnsutils iputils-ping && \
    mkdir -p /etc/apt/keyrings/ && \
    wget -O- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null && \
    echo "deb [arch=amd64,armhf,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | \
    tee /etc/apt/sources.list.d/microsoft.list && \
    apt-get update -y && apt-get install -y sqlcmd && apt-get remove -y gnupg wget && apt-get autoremove -y && apt-get clean -y

COPY --from=docker.io/fullstorydev/grpcurl:latest /bin/grpcurl /bin/grpcurl

ARG NATS_VERSION=0.1.1

RUN curl -sSL https://github.com/nats-io/natscli/releases/download/v${NATS_VERSION}/nats-${NATS_VERSION}-amd64.deb -o nats.deb && \
    dpkg -i nats.deb && rm nats.deb

ENV SQLCMDMAXVARTYPEWIDTH=65535 \
    SQLCMDCOLSEP="," \
    SQLCMDHEADERS=-1
